name: TryHackMe Badge Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update TryHackMe Badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: 'Svqxcw'
          image_path: 'thm-badge.png'

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update TryHackMe badge" || exit 0
          git push
